move import-certificates.sh into CircleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,46 +16,79 @@ aliases:
       - equal: [ develop, << pipeline.git.branch >> ]
       - equal: [ main, << pipeline.git.branch >> ]
       - equal: [ master, << pipeline.git.branch >> ]
+commands:
+  prepare_certificates:
+    description: "This command prepares SSL certificates in the Certificates directory."
+    steps:
+      - unless:
+          condition:
+            *should_sign
+          steps:
+            - run:
+                name: Generate mock SSL certificates
+                working_directory: ./Certificates
+                shell: bash
+                command: ./mock-certificates.sh
+      - when:
+          condition:
+            *should_sign
+          steps:
+            - run:
+                name: Import from CI context
+                working_directory: ./Certificates
+                shell: bash
+                command: |
+                  set -e
+                  function decodeToFile () {
+                    if [ -z "$1" ]; then
+                      echo "Missing or invalid filename"
+                      return 1
+                    fi
+                    if [ -z "$2" ]; then
+                      echo "Missing environment variable contents for file: $1"
+                      return 2
+                    fi
+                    echo "$2" | base64 --decode > "$1"
+                  }
+                  echo "Importing SSL certificate"
+                  decodeToFile scratch-device-manager.cer "${SDM_CERT}"
+                  decodeToFile certificate-authority.cer "${SDM_CERT_CA}"
+                  decodeToFile intermediate.cer "${SDM_CERT_INT}"
+                  decodeToFile scratch-device-manager.key "${SDM_CERT_KEY}"
+                  echo "Importing OS-specific imformation (OSTYPE=${OSTYPE})"
+                  if [[ "$OSTYPE" == "darwin"* ]]; then
+                    decodeToFile code-to-learn-macos.p12 "${CSC_MACOS}"
+                  fi
+      - run:
+          name: Convert SSL certificates
+          working_directory: ./Certificates
+          shell: bash
+          command: ./convert-certificates.sh
 jobs:
   build_for_mac:
     macos:
       xcode: "11.3.1"
     steps:
       - checkout
+      - prepare_certificates
       - when:
           condition:
             *should_sign
           steps:
-              - run:
-                  name: Import from CI context
-                  working_directory: ./Certificates
-                  command: ./import-certificates.sh
-              - run:
-                  name: Set up code-signing keychain
-                  # DO NOT RUN THIS on your own computer unless you really know what you're doing!
-                  command: |
-                    security -v create-keychain -p circleci circleci.keychain
-                    security -v default-keychain -s circleci.keychain
-                    security -v import Certificates/code-to-learn-macos.p12 -k circleci.keychain -P "" -T /usr/bin/codesign -T /usr/bin/productbuild
-                    security -v unlock-keychain -p circleci circleci.keychain
-                    # "set-key-partition-list" prints extensive not-so-useful output and adding "-q" (even multiple times) doesn't suppress it.
-                    # The "grep -v" at the end of this line suppresses all of that so any errors or warnings might be more visible.
-                    security -v set-key-partition-list -S apple-tool:,apple:,codesign: -s -k circleci circleci.keychain | grep -v '^    0x'
-                    security -v set-keychain-settings -lut 600 circleci.keychain
-                    security -v find-identity circleci.keychain
-                    rm Certificates/code-to-learn-macos.p12
-      - unless:
-          condition:
-            *should_sign
-          steps:
-              - run:
-                  name: Generate mock SSL certificates
-                  working_directory: ./Certificates
-                  command: ./mock-certificates.sh
-      - run:
-          name: Convert SSL certificates
-          working_directory: ./Certificates
-          command: ./convert-certificates.sh
+            - run:
+                name: Set up code-signing keychain
+                # DO NOT RUN THIS on your own computer unless you really know what you're doing!
+                command: |
+                  security -v create-keychain -p circleci circleci.keychain
+                  security -v default-keychain -s circleci.keychain
+                  security -v import Certificates/code-to-learn-macos.p12 -k circleci.keychain -P "" -T /usr/bin/codesign -T /usr/bin/productbuild
+                  security -v unlock-keychain -p circleci circleci.keychain
+                  # "set-key-partition-list" prints extensive not-so-useful output and adding "-q" (even multiple times) doesn't suppress it.
+                  # The "grep -v" at the end of this line suppresses all of that so any errors or warnings might be more visible.
+                  security -v set-key-partition-list -S apple-tool:,apple:,codesign: -s -k circleci circleci.keychain | grep -v '^    0x'
+                  security -v set-keychain-settings -lut 600 circleci.keychain
+                  security -v find-identity circleci.keychain
+                  rm Certificates/code-to-learn-macos.p12
       - restore_cache:
           name: Restore Homebrew cache
           key: homebrew-cache-v2
@@ -94,20 +127,21 @@ jobs:
           condition:
             *should_sign
           steps:
-              - run:
-                  name: Sign the application
-                  command: make --directory=macOS dist
-              - run:
-                  name: Move signed build products to Artifacts directory
-                  command: |
-                    mkdir -p macOS/Artifacts/
-                    mv -v macOS/dist/{scratch-link,mas-scratch-link}-*.pkg macOS/Artifacts/
+            - run:
+                name: Sign the application
+                command: make --directory=macOS dist
+            - run:
+                name: Move signed build products to Artifacts directory
+                command: |
+                  mkdir -p macOS/Artifacts/
+                  mv -v macOS/dist/{scratch-link,mas-scratch-link}-*.pkg macOS/Artifacts/
       - store_artifacts:
           path: macOS/Artifacts/
   build_for_windows:
     executor: windows/default
     steps:
       - checkout
+      - prepare_certificates
       - when:
           condition:
             *should_sign
